package com.backend.repo;

public class FeeStructureData {
	private String data="{\r\n"
			+ "  \"Exam Fee\": {\r\n"
			+ "    \"INDIAN\": {\r\n"
			+ "      \"Medical\": {\r\n"
			+ "        \"PG\": {\r\n"
			+ "          \"amount\": 400\r\n"
			+ "        },\r\n"
			+ "        \"UG\": {\r\n"
			+ "          \"amount\": 400\r\n"
			+ "        },\r\n"
			+ "        \"DIPLOMA\": {\r\n"
			+ "          \"amount\": 400\r\n"
			+ "        },\r\n"
			+ "        \"Ph.D\": {\r\n"
			+ "          \"amount\": 400\r\n"
			+ "        }\r\n"
			+ "      },\r\n"
			+ "      \"Ayurveda\": {\r\n"
			+ "        \"PG\": {\r\n"
			+ "          \"amount\": 400\r\n"
			+ "        },\r\n"
			+ "        \"UG\": {\r\n"
			+ "          \"amount\": 400\r\n"
			+ "        },\r\n"
			+ "        \"DIPLOMA\": {\r\n"
			+ "          \"amount\": 400\r\n"
			+ "        },\r\n"
			+ "        \"Ph.D\": {\r\n"
			+ "          \"amount\": 400\r\n"
			+ "        }\r\n"
			+ "      },\r\n"
			+ "      \"Dental\": {\r\n"
			+ "        \"PG\": {\r\n"
			+ "          \"amount\": 400\r\n"
			+ "        },\r\n"
			+ "        \"UG\": {\r\n"
			+ "          \"amount\": 400\r\n"
			+ "        },\r\n"
			+ "        \"DIPLOMA\": {\r\n"
			+ "          \"amount\": 400\r\n"
			+ "        },\r\n"
			+ "        \"Ph.D\": {\r\n"
			+ "          \"amount\": 400\r\n"
			+ "        }\r\n"
			+ "      }\r\n"
			+ "    },\r\n"
			+ "    \"FOREIGN\": {\r\n"
			+ "      \"Medical\": {\r\n"
			+ "        \"PG\": {\r\n"
			+ "          \"amount\": 100\r\n"
			+ "        },\r\n"
			+ "        \"UG\": {\r\n"
			+ "          \"amount\": 100\r\n"
			+ "        },\r\n"
			+ "        \"DIPLOMA\": {\r\n"
			+ "          \"amount\": 100\r\n"
			+ "        },\r\n"
			+ "        \"Ph.D\": {\r\n"
			+ "          \"amount\": 100\r\n"
			+ "        }\r\n"
			+ "      },\r\n"
			+ "      \"Ayurveda\": {\r\n"
			+ "        \"PG\": {\r\n"
			+ "          \"amount\": 100\r\n"
			+ "        },\r\n"
			+ "        \"UG\": {\r\n"
			+ "          \"amount\": 100\r\n"
			+ "        },\r\n"
			+ "        \"DIPLOMA\": {\r\n"
			+ "          \"amount\": 100\r\n"
			+ "        },\r\n"
			+ "        \"Ph.D\": {\r\n"
			+ "          \"amount\": 100\r\n"
			+ "        }\r\n"
			+ "      },\r\n"
			+ "      \"Dental\": {\r\n"
			+ "        \"PG\": {\r\n"
			+ "          \"amount\": 100\r\n"
			+ "        },\r\n"
			+ "        \"UG\": {\r\n"
			+ "          \"amount\": 100\r\n"
			+ "        },\r\n"
			+ "        \"DIPLOMA\": {\r\n"
			+ "          \"amount\": 100\r\n"
			+ "        },\r\n"
			+ "        \"Ph.D\": {\r\n"
			+ "          \"amount\": 100\r\n"
			+ "        }\r\n"
			+ "      }\r\n"
			+ "    },\r\n"
			+ "    \"NRI\": {\r\n"
			+ "      \"Medical\": {\r\n"
			+ "        \"PG\": {\r\n"
			+ "          \"amount\": 600\r\n"
			+ "        },\r\n"
			+ "        \"UG\": {\r\n"
			+ "          \"amount\": 600\r\n"
			+ "        },\r\n"
			+ "        \"DIPLOMA\": {\r\n"
			+ "          \"amount\": 600\r\n"
			+ "        },\r\n"
			+ "        \"Ph.D\": {\r\n"
			+ "          \"amount\": 600\r\n"
			+ "        }\r\n"
			+ "      },\r\n"
			+ "      \"Ayurveda\": {\r\n"
			+ "        \"PG\": {\r\n"
			+ "          \"amount\": 600\r\n"
			+ "        },\r\n"
			+ "        \"UG\": {\r\n"
			+ "          \"amount\": 600\r\n"
			+ "        },\r\n"
			+ "        \"DIPLOMA\": {\r\n"
			+ "          \"amount\": 600\r\n"
			+ "        },\r\n"
			+ "        \"Ph.D\": {\r\n"
			+ "          \"amount\": 600\r\n"
			+ "        }\r\n"
			+ "      },\r\n"
			+ "      \"Dental\": {\r\n"
			+ "        \"PG\": {\r\n"
			+ "          \"amount\": 600\r\n"
			+ "        },\r\n"
			+ "        \"UG\": {\r\n"
			+ "          \"amount\": 600\r\n"
			+ "        },\r\n"
			+ "        \"DIPLOMA\": {\r\n"
			+ "          \"amount\": 600\r\n"
			+ "        },\r\n"
			+ "        \"Ph.D\": {\r\n"
			+ "          \"amount\": 600\r\n"
			+ "        }\r\n"
			+ "      }\r\n"
			+ "    },\r\n"
			+ "    \"SAARC\": {\r\n"
			+ "      \"Medical\": {\r\n"
			+ "        \"PG\": {\r\n"
			+ "          \"amount\": 600\r\n"
			+ "        },\r\n"
			+ "        \"UG\": {\r\n"
			+ "          \"amount\": 600\r\n"
			+ "        },\r\n"
			+ "        \"DIPLOMA\": {\r\n"
			+ "          \"amount\": 600\r\n"
			+ "        },\r\n"
			+ "        \"Ph.D\": {\r\n"
			+ "          \"amount\": 600\r\n"
			+ "        }\r\n"
			+ "      },\r\n"
			+ "      \"Ayurveda\": {\r\n"
			+ "        \"PG\": {\r\n"
			+ "          \"amount\": 600\r\n"
			+ "        },\r\n"
			+ "        \"UG\": {\r\n"
			+ "          \"amount\": 600\r\n"
			+ "        },\r\n"
			+ "        \"DIPLOMA\": {\r\n"
			+ "          \"amount\": 600\r\n"
			+ "        },\r\n"
			+ "        \"Ph.D\": {\r\n"
			+ "          \"amount\": 600\r\n"
			+ "        }\r\n"
			+ "      },\r\n"
			+ "      \"Dental\": {\r\n"
			+ "        \"PG\": {\r\n"
			+ "          \"amount\": 600\r\n"
			+ "        },\r\n"
			+ "        \"UG\": {\r\n"
			+ "          \"amount\": 600\r\n"
			+ "        },\r\n"
			+ "        \"DIPLOMA\": {\r\n"
			+ "          \"amount\": 600\r\n"
			+ "        },\r\n"
			+ "        \"Ph.D\": {\r\n"
			+ "          \"amount\": 600\r\n"
			+ "        }\r\n"
			+ "      }\r\n"
			+ "    }\r\n"
			+ "  },\r\n"
			+ "  \"Application Fee\": {\r\n"
			+ "    \"INDIAN\": {\r\n"
			+ "      \"Medical\": {\r\n"
			+ "        \"UG\": {\r\n"
			+ "          \"amount\": 200\r\n"
			+ "        },\r\n"
			+ "        \"UG-DIPLOMA\": {\r\n"
			+ "          \"amount\": 300\r\n"
			+ "        },\r\n"
			+ "        \"PG\": {\r\n"
			+ "          \"amount\": 500\r\n"
			+ "        }\r\n"
			+ "      },\r\n"
			+ "      \"Ayurveda\": {\r\n"
			+ "        \"UG\": {\r\n"
			+ "          \"amount\": 200\r\n"
			+ "        },\r\n"
			+ "        \"UG-DIPLOMA\": {\r\n"
			+ "          \"amount\": 300\r\n"
			+ "        },\r\n"
			+ "        \"PG\": {\r\n"
			+ "          \"amount\": 500\r\n"
			+ "        }\r\n"
			+ "      },\r\n"
			+ "      \"Dental\": {\r\n"
			+ "        \"UG\": {\r\n"
			+ "          \"amount\": 200\r\n"
			+ "        },\r\n"
			+ "        \"UG-DIPLOMA\": {\r\n"
			+ "          \"amount\": 300\r\n"
			+ "        },\r\n"
			+ "        \"PG\": {\r\n"
			+ "          \"amount\": 500\r\n"
			+ "        }\r\n"
			+ "      }\r\n"
			+ "    },\r\n"
			+ "    \"FOREIGN\": {\r\n"
			+ "      \"Medical\": {\r\n"
			+ "        \"UG\": {\r\n"
			+ "          \"amount\": 400\r\n"
			+ "        },\r\n"
			+ "        \"UG-DIPLOMA\": {\r\n"
			+ "          \"amount\": 400\r\n"
			+ "        },\r\n"
			+ "        \"PG\": {\r\n"
			+ "          \"amount\": 700\r\n"
			+ "        }\r\n"
			+ "      },\r\n"
			+ "      \"Dental\": {\r\n"
			+ "        \"UG\": {\r\n"
			+ "          \"amount\": 400\r\n"
			+ "        },\r\n"
			+ "        \"UG-DIPLOMA\": {\r\n"
			+ "          \"amount\": 400\r\n"
			+ "        },\r\n"
			+ "        \"PG\": {\r\n"
			+ "          \"amount\": 700\r\n"
			+ "        }\r\n"
			+ "      },\r\n"
			+ "      \"Ayurveda\": {\r\n"
			+ "        \"UG\": {\r\n"
			+ "          \"amount\": 400\r\n"
			+ "        },\r\n"
			+ "        \"UG-DIPLOMA\": {\r\n"
			+ "          \"amount\": 400\r\n"
			+ "        },\r\n"
			+ "        \"PG\": {\r\n"
			+ "          \"amount\": 700\r\n"
			+ "        }\r\n"
			+ "      }\r\n"
			+ "    }\r\n"
			+ "  }\r\n"
			+ "}" ;

	public String getData() {
		return data;
	}

	public void setData(String data) {
		this.data = data;
	}
	
}
